# Generated by Django 4.1.3 on 2022-12-06 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Exam')),
                ('modaliti', models.CharField(choices=[('CT', 'CT-Scan'), ('MR', 'MRI'), ('XR', 'General X-Ray'), ('MG', 'Mammography'), ('US', 'Ultrasound'), ('FL', 'Fluoroscopy'), ('XA', 'Angiography'), ('MF', 'Mobile Fluoro/OT/ERCP')], default='XR', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'RIS',
            },
        ),
        migrations.CreateModel(
            name='Smrp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jxr', models.CharField(max_length=150)),
                ('modified', models.DateField(auto_now=True)),
                ('ris', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.ris', verbose_name='RIS')),
            ],
            options={
                'verbose_name_plural': 'SMRP',
            },
        ),
    ]
