# Generated by Django 4.1.3 on 2022-12-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smrp',
            name='modaliti',
            field=models.CharField(choices=[('CT', 'CT-Scan'), ('MR', 'MRI'), ('XR', 'General X-Ray'), ('MG', 'Mammography'), ('US', 'Ultrasound'), ('FL', 'Fluoroscopy'), ('XA', 'Angiography'), ('MF', 'Mobile Fluoro/OT/ERCP'), ('HC', 'Hardcopy'), ('DI', 'Digitize'), ('RE', 'Rad Resources'), ('RC', 'Ref Consult')], default='XR', max_length=50),
        ),
        migrations.AlterField(
            model_name='ris',
            name='modaliti',
            field=models.CharField(choices=[('CT', 'CT-Scan'), ('MR', 'MRI'), ('XR', 'General X-Ray'), ('MG', 'Mammography'), ('US', 'Ultrasound'), ('FL', 'Fluoroscopy'), ('XA', 'Angiography'), ('MF', 'Mobile Fluoro/OT/ERCP'), ('HC', 'Hardcopy'), ('DI', 'Digitize'), ('RE', 'Rad Resources'), ('RC', 'Ref Consult')], default='XR', max_length=50),
        ),
    ]
