# Generated by Django 4.1.3 on 2022-12-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_smrp_modaliti_alter_ris_modaliti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smrp',
            name='jxr',
        ),
        migrations.RemoveField(
            model_name='smrp',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='smrp',
            name='ris',
        ),
        migrations.AddField(
            model_name='ris',
            name='jxr',
            field=models.CharField(default='Harris', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ris',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
