# Generated by Django 4.1.3 on 2022-12-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_ris_smrp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ris',
            options={'ordering': ['modaliti', 'name'], 'verbose_name_plural': 'RIS'},
        ),
    ]
